@startuml
autonumber
hide footbox

title SD - Specify Product

		participant ":SpecifyProductUI" as ui
		participant ":SpecifyProductController" as ctrl
		participant ":PersistenceContext" as pc
		participant ":RepositoryFactory" as rf
		participant ":ProductCategoryRepository" as repoPC
		participant ":NutricionalInfo" as ni
		participant ":Product" as prod
		participant ":ProductRepository" as repo

		ui->ctrl:create
		ui->ctrl:getProductCategory
		activate ctrl
		ctrl->pc:repositories()
		pc->rf:create
		rf->repoPC:create
		ctrl->repoPC:findAll
		activate repoPC
		deactivate repoPC
		ctrl-->ui:ProductCategory
		deactivate ctrl

		ui->ui:doShow()
		ui->ctrl:registerProduct(cat, name, cal, salt)
        activate ctrl

		ctrl->ni:ni = create(cal, salt)
		activate ni
		deactivate ni
		ctrl->prod:newProduct = create(cat, name, ni)
        activate prod
        deactivate prod

		ctrl->pc:repositories()
		activate pc
		pc->rf:create
		activate rf
		rf->repo:create
		activate repo
		deactivate repo
		deactivate rf
		deactivate pc
		ctrl->repo:save(newProduct)
		activate repo
		deactivate repo
		deactivate ctrl


@enduml