@startuml
autonumber
actor "SalesClerk" as SC

activate SC
SC -> ":System" : inicia a especificação de uma nova categoria
activate ":System"
":System" --> SC : solicita o código alfanumérico e a descrição da categoria
deactivate ":System"
SC -> ":System" : insere a informação
activate ":System"
":System" --> SC : informa do sucesso da operação
deactivate ":System"

deactivate SC

@enduml

