@startuml
autonumber
actor "SalesClerk" as SC
participant "SpecifyCategoryUI" as UI <<presentation>>
participant "SpeficyCategoryController" as CTRL <<application>>
participant PersistenceContext as PER <<persistence>>
participant "RepositoryFactory" as REPOFACT <<factory>>
participant "category : Category" as CUST <<domain>>
database "CategoryRepository" as custREPO <<repository>>



activate SC
SC -> UI : inicia a especificação de uma nova categoria
activate UI
UI --> SC : solicita o código alfanumérico e a descrição da categoria
SC -> UI : submete informação
UI -> CTRL : specifyCategory(alphaNumericCode,description);
activate CTRL
CTRL -> PER : repositories()
activate PER
PER -> REPOFACT : create
PER --> CTRL : factory
deactivate PER
CTRL -> REPOFACT : categories()
activate REPOFACT
REPOFACT -> custREPO : create
REPOFACT --> CTRL : categoryRepository
deactivate REPOFACT
CTRL -> CUST : specifyCategory(alphaNumericCode,description);
CTRL -> custREPO: save(Category);
CTRL -> UI : category
UI --> SC : informa do sucesso da operação e mostra a categoria criada
deactivate UI
deactivate SC

@enduml
