@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Warehouse <<entity>>{
  -
}

class WarehousePlant <<value object>>{
  - 
}

class Survey <<entity>>{
  -code
  -description
  -period
}

class SurveyRule <<value object>>{
  - 
}

class ShipmentMethod <<value object>>{
  -name
  -cost
  -volume
  -weight
}

class Shipment <<entity>>{
  - 
}

class StorageArea <<value object>>{
  - aisleId
  - rowId
  - shelfId
}

class Bin <<value object>>{
  -size
}

class Questionnaire <<value object>>{
  - 
}

class Notification <<entity>>{
  - 
}

class SurveyAnswers <<value entity>>{
  -
}

class AGV <<entity>> {
  -id
  -shortDescription
  -maxWeight
  -baseLocation
  -autonomyStatus
}

class AGVModel <<value object>> {
  -
}

class AGVTask <<entity>>{
  - 
}

class Order <<entity>>{
  -id
  -dateTime
  -listProductsPricesQuantity
  -totalPriceWIthAndWithoutTaxes
  -registryUser
  -state
}

class Payment <<entity>>{
  - 
}

class PaymentMethod <<value object>>{
  - 
}

class PaymentConfirmation <<value object>>{
  - confirmationText
}

class ProductCategory <<value object>>{
  -code
  -description
}

class Product <<entity>>{
  -code
  -setOfPhotos
  -reference
  -barcode(has standard daclarations)
  -[productioncode]
  -listOfPricesPerCountryWithOrWithTaxes
  -availableForOrder
}

class ProductDescription <<value object>>{
  -shortDescription
  -extendedDescription
  -technicalDescription
}

class Brand <<entity>>{
  -name 
}

class ProductCatalog <<entity>>{
  -
}

class User <<entity>>{
  -  
}

class Customer <<entity>>{
  -id
  -name
  -VAT
}

class Email <<value object>>{
  -
}

class PhoneNumber <<value object>>{
  -
}

class PostalAddress <<value object>> {
  - 
}

class BirthDate <<value object>>{
  -
}

class Gender <<value object>>{
  -
}

class SalesManager <<entity>>{
  - 
}

class WarehouseEmployee <<entity>>{
  -  
}

class Administrator <<entity>>{
 - 
}

class SalesClerk <<entity>>{
  - 
}

class SalesReport <<entity>>{
  -
}

class ShoppingCart <<entity>>{
  - 
}



Customer "1" -- "1" User : é >
Customer "1" -- "1" ShoppingCart : tem >
Customer "1" -- "0..*" SurveyAnswers : dá >
Customer "1" -- "0..*" Notification : recebe >
Customer "1" -- "1" Email : tem >
Customer "1" -- "1" PhoneNumber : tem >
Customer "1" -- "1..*" PostalAddress : tem >
Customer "1" -- "1" BirthDate : tem >
Customer "1" -- "1" Gender : tem >
Customer "1" -- "1" PaymentConfirmation : confirma >
SalesClerk "1" -- "1" User : é >
SalesClerk "1" -- "0..*" Product : regista >
SalesClerk "1..*" -- "1..*" ProductCatalog : gere >
SalesClerk "1..*" -- "1..*" ProductCategory : gere >
SalesClerk "1" -- "0..*" Customer : regista >
SalesClerk "1" -- "0..*" Order : regista >
WarehouseEmployee "1" -- "1" User : é >
SalesManager "1" -- "1" User : é >
SalesManager "1" -- "0..*" Product : regista >
SalesManager "1" -- "0..*" Customer : regista >
SalesManager "1" -- "0..*" Order : regista >
SalesManager "1..*" -- "1..*" ProductCatalog : gere >
SalesManager "1..*" -- "1..*" ProductCategory : gere >
SalesManager "1..*" -- "1..*" SalesReport : acede >
SalesManager "1" -- "0..*" Survey : cria >
Product "0..*" -- "1" ProductCategory : tem >
Product "1" -- "1" ProductDescription : descrito em >
Brand "1" -- "1..*" Product : fabrica >
Warehouse "1" -- "1" WarehousePlant : tem >
WarehousePlant -- StorageArea : tem >
Shipment "1" -- "1" ShipmentMethod : tem >
Shipment "1" -- "1*" Order : tem >
Payment "1" -- "1" PaymentMethod : tem >
Payment "1" -- "1" PaymentConfirmation : necessita >
AGV "1" -- "0..*" AGVTask : realiza >
AGVTask "1" -- "1" Order : refere-se a >
Order "0..*" -- "1..*" Product : tem >
Order "1" -- "1" Payment : tem >
Order "0..*" -- "1" Customer : em nome de >
Order "0..*" -- "1" PaymentMethod : guarda >
Order "0..*" -- "1" ShipmentMethod : guarda >
Order "1..*" -- "1" PostalAddress : enviado para >
ShoppingCart "1" -- "1" Order : origina >
ShoppingCart "0..*" -- "1..*" Product : tem >
Bin "1" -- "1" Product : tem >
StorageArea "1" -- "1..*" Bin : contém >
ProductCatalog "1" -- "1..*" Product : contém >
ProductCatalog "1" -- "1*" Customer : visto por >
Survey "1" -- "1" SurveyAnswers : guarda >
Survey "0..*" -- "1" Customer : referente a >
Survey "1" -- "1" Notification : envia >
Survey "1" -- "1" Questionnaire : contém >
Survey "1..*" -- "1..*" SurveyRule : varia mediante >
Questionnaire "0..*" -- "1" Customer : respondido por >
WarehouseEmployee "1..*" -- "1..*" Warehouse : gere >
WarehouseEmployee "1..*" -- "1..*" WarehousePlant : gere >
WarehouseEmployee "1..*" -- "1..*" AGV : gere >
SurveyAnswers "1" -- "1" SalesReport : origina >
Administrator "1" -- "1" User : é >
Administrator "1..*" -- "1..*" User : gere >
User "1" -- "0..*" Order : efetua >





@enduml
