@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0

package Warehouse <<Folder>> {
class Warehouse <<entity root>>{
  -
}

class WarehousePlant <<value object>>{
  - 
}
  
class StorageArea <<value object>>{
  - aisleId
  - rowId
  - shelfId
}

class Bin <<value object>>{
  -size
}
}


package Shipment <<Folder>>{
class Shipment <<entity root>>{
  - 
}

class ShipmentMethod <<value object>>{
  -name
  -cost
  -volume
  -weight
}
}

package Survey <<Folder>>{
class Survey <<entity root>>{
  -code
  -period
}

class SurveyDescription <<value object>>{
  - 
}
  
class SurveyRule <<value object>>{
  - 
}
  
class Questionnaire <<value object>>{
  - 
}

class Notification <<entity>>{
  - 
}

class SurveyAnswers <<value entity>>{
  -
}
}
  
package AGV <<Folder>>{
class AGV <<entity root>> {
  -id
  -maxWeight
  -baseLocation
  -autonomyStatus
}

class AGVShortDescription <<value object>>{
  - 
}

class AGVModel <<value object>> {
  -
}
}

package AGVTask <<Folder>>{
class AGVTask <<entity root>>{
  - 
}
  
class ManualTask <<entity>>{
  - 
}
  
class AutomaticTask <<entity>>{
  - 
}
}
  
package Order <<Folder>>{
class Order <<entity>>{
  -id
  -dateTime
  -listProductsPricesQuantity
  -totalPriceWIthAndWithoutTaxes
  -registryUser
}
  
class OrderState <<Enum>>{
  - 
}
  
class PriceO <<value object>>{
  -price
}
  
}

package Payment <<Folder>>{
class Payment <<entity root>>{
  - 
}

class PaymentMethod <<value object>>{
  - 
}

class PaymentConfirmation <<value object>>{
  - confirmationText
}
}

package Product <<Folder>>{
class Product <<entity root>>{
  -code
  -reference
  -availableForOrder
}

class Photo <<value object>>{
  - 
}

class Barcode <<value object>>{
  - 
}

class ProductionCode <<value object>>{
  - 
}

class Price <<value object>>{
  -price
}

class ProductDescription <<value object>>{
  -shortDescription
  -extendedDescription
  -technicalDescription
}
  
class Brand <<entity>>{
  -name 
}  
}

package ProductCategory <<Folder>>{
class ProductCategory <<value object>>{
  -code
}
  
class CategoryDescription <<value object>>{
  -description
}
}

class ProductCatalog <<entity>>{
  -
}

package Customer <<Folder>> {
class Customer <<entity root>>{
  -id
  -gender
  -birthDate
}

class VAT <<value object>>{
  -
}

class PhoneNumber <<value object>>{
  -
}


class Address <<value object>> {
  - 
} 
}

package User <<Folder>>{
class User <<entity root>>{
  -  
}

class Name <<value object>>{
  -
}

class Email <<value object>>{
  -
}

class Password <<value object>>{
  -
}

class SalesManager <<entity>>{
  - 
}

class WarehouseEmployee <<entity>>{
  -  
}

class Administrator <<entity>>{
 - 
}

class SalesClerk <<entity>>{
  - 
}
}

class SalesReport <<entity>>{
  -
}

package ShoppingCart <<Folder root>>{
class ShoppingCart <<entity>>{
  - 
}

class PriceSC <<value object>>{
  -price
}
}


Customer "1" -- "1" User : é >
Customer "1" -- "1" ShoppingCart : tem >
Customer "1" -- "0..*" SurveyAnswers : dá >
Customer "1" -- "0..*" Notification : recebe >
User "1" -- "1" Name : tem >
User "1" -- "1" Password : tem >
User "1" -- "1" Email : tem >
Customer "1" -- "1" PhoneNumber : tem >
Customer "1" -- "1" VAT : tem >
Customer "1" -- "1..*" Address : tem BillingAddress >
Customer "1" -- "1..*" Address : tem ShippingAddress >
Customer "1" -- "1" PaymentConfirmation : confirma >
SalesClerk "1" -- "1" User : é >
SalesClerk "1" -- "0..*" Product : regista >
SalesClerk "1..*" -- "1..*" ProductCatalog : gere >
SalesClerk "1..*" -- "1..*" ProductCategory : gere >
SalesClerk "1" -- "0..*" Customer : regista >
SalesClerk "1" -- "0..*" Order : regista >
WarehouseEmployee "1" -- "1" User : é >
SalesManager "1" -- "1" User : é >
SalesManager "1" -- "0..*" Product : regista >
SalesManager "1" -- "0..*" Customer : regista >
SalesManager "1" -- "0..*" Order : regista >
SalesManager "1..*" -- "1..*" ProductCatalog : gere >
SalesManager "1..*" -- "1..*" ProductCategory : gere >
SalesManager "1..*" -- "1..*" SalesReport : acede >
SalesManager "1" -- "0..*" Survey : cria >
Product "0..*" -- "1" ProductCategory : tem >
Product "1" -- "1" ProductDescription : descrito em >
Product "1" -- "1..*" Photo : tem >
Product "1" -- "1" Barcode : tem >
Product "1" -- "1" ProductionCode : tem >
Product "1" -- "1" Price : tem preço sem taxa >
Product "1" -- "1" Price : tem preço com taxa >
Brand "1" -- "1..*" Product : fabrica >
Warehouse "1" -- "1" WarehousePlant : tem >
WarehousePlant -- StorageArea : tem >
Shipment "1" -- "1" ShipmentMethod : tem >
Shipment "1" -- "1*" Order : tem >
Payment "1" -- "1" PaymentMethod : tem >
Payment "1" -- "1" PaymentConfirmation : necessita >
AGV "1" -- "0..*" AGVTask : realiza >
AGV "1" -- "1" AGVShortDescription : tem >
AGV "1" -- "1" AGVModel : tem >
AGVTask "1" -- "1" Order : refere-se a >
ManualTask "1" -- "1" AGVTask : é >
AutomaticTask "1" -- "1" AGVTask : é >
Order "0..*" -- "1..*" Product : tem >
Order "1" -- "1" Payment : tem >
Order "0..*" -- "1" Customer : em nome de >
Order "0..*" -- "1" PaymentMethod : guarda >
Order "0..*" -- "1" ShipmentMethod : guarda >
Order "1..*" -- "1" Address : efetuado em BillingAddress >
Order "1..*" -- "1" Address : enviado para ShippingAddress >
Order "1" -- "1..*" PriceO : tem preço sem taxa >
Order "1" -- "1..*" PriceO : tem preço com taxa >
ShoppingCart "1" -- "1" Order : origina >
ShoppingCart "0..*" -- "1..*" Product : tem >
ShoppingCart "1" -- "1" PriceSC : tem preço sem taxa >
ShoppingCart "1" -- "1" PriceSC : tem preço com taxa >
Bin "1" -- "1" Product : tem >
StorageArea "1" -- "1..*" Bin : contém >
ProductCatalog "1" -- "1..*" Product : contém >
ProductCatalog "1" -- "1*" Customer : visto por >
Survey "1" -- "1" SurveyAnswers : guarda >
Survey "0..*" -- "0..*" Customer : referente a >
Survey "1" -- "1" Notification : envia >
Survey "1" -- "1" Questionnaire : contém >
Survey "1" -- "1" SurveyDescription : tem >
Survey "1..*" -- "1..*" SurveyRule : varia mediante >
Questionnaire "0..*" -- "0..*" Customer : respondido por >
WarehouseEmployee "1..*" -- "1..*" Warehouse : gere >
WarehouseEmployee "1..*" -- "1..*" WarehousePlant : gere >
WarehouseEmployee "1..*" -- "1..*" AGV : gere >
SurveyAnswers "1" -- "1" SalesReport : origina >
Administrator "1" -- "1" User : é >
Administrator "1..*" -- "1..*" User : gere >
User "1" -- "0..*" Order : efetua >





@enduml
