@startuml
autonumber
actor "Customer" as C

activate C
C -> ":System" : inicia a visualizacao do catalogo de produtos
activate ":System"
loop for each produto
":System" --> C : apresenta o catalogo de produtos e solicita id do produto
deactivate ":System"
C -> ":System" : submete informação
activate ":System"
":System" -> C : informa do sucesso da operação
deactivate ":System"
end
deactivate C

@enduml