@startuml
autonumber
hide footbox

title SD - Automatic task assignment

actor "Project Manager" as C

		participant ":AutomaticTaskController" as ui
		participant ":PersistenceContext" as pc
		participant ":RepositoryFactory" as rf
		participant ":Order" as prod
		participant ":OrderRepository" as repoC
		participant ":TaskRepository" as repoT
		participant ":AGVRepository" as repoA

        activate C
        C->ui:Automatic task assignment.
        deactivate C
        activate ui
        ui->repoA:  List<AGV> AvailableAGVs()
        activate repoA
        repoA -> ui : AvailableAGVs
        deactivate repoA
        ui -> repoC:List<Order> OrderList()
         activate repoC
        repoC -> ui: OrderList
         deactivate repoC
         ui->ui: List<Order> fifo()
         ui->ui: List<Task> createTask()

         ui->pc: repositories();
         activate pc
         pc->rf: save(task)
         activate rf
         rf->repoT: save(task)
         activate repoT
         deactivate pc
          deactivate rf
          ui->C: success
           deactivate ui










@enduml