@startuml
autonumber
hide footbox

title SD - Register Customer

		participant ":TaskAssignUI" as ui
		participant ":TaskAssignController" as ctrl
		participant ":PersistenceContext" as pc
		participant ":RepositoryFactory" as rf
		participant ":OrderRepository" as repoPC
        participant ":Order" as prod
		ui->ui:doShow()
        		ui->ctrl:addCustomer(cat, name, cal, salt)


        		ctrl->prod:newCustomer = create(cat, name, ni)

        		ctrl->pc:repositories()
        		pc->rf:create
        		rf->repoPC:create
        		ctrl->repoPC:save(newCustomer)




@enduml