@startuml
autonumber
actor "Customer" as CU
participant "CheckOrderStatusUI" as UI <<presentation>>
participant "CheckOrderStatusController" as CTRL <<application>>
participant "customer : Customer" as CUST <<domain>>
database "CustomerRepository" as custREPO <<repository>>
database "OrderRepository" as orderREPO <<repository>>



activate CU
CU -> UI : pretende verificar o status das suas orders
activate UI
UI-> CU : pede o id do cliente
CU-> UI : insere o seu id de cliente
UI -> CTRL : findCustomerById(new VATiD(customerId))
activate CTRL
CTRL -> custREPO : findCustomerById(new VATiD(customerId))
CTRL -> CTRL : checkOrderStatus()
CTRL-> orderREPO : orderRepository.findOrderByClient(customer);

UI --> CU : informa do sucesso da operação e mostra o status das suas operacoes
deactivate UI
deactivate CU

@enduml
