@startuml

autonumber

actor "SalesClerk" as SC

participant ":SearchProductCatalogUI" as UI
participant ":SearchProductCatalogController" as CTRL
participant ":SearchProductCatalogService" as SERV
participant ":PersistenceContext" as PERS
participant ":RepositoryFactory" as REPF
participant ":ProductCatalogRepository" as REP


activate SC

SC -> UI : Asks to view the Product Catalog
activate UI

UI -> CTRL : create()
activate CTRL

CTRL -> SERV : create()
activate SERV

SERV -> PERS : repositories()

PERS -> REPF : create()

activate REPF

REPF -> REP : create()

deactivate REPF

REP --> SERV


SERV --> CTRL
deactivate SERV


CTRL --> UI
deactivate CTRL


UI --> SC : Asks what he wants to filter

SC -> UI : Gives filter options

UI --> SC : Asks how he wants to sort the data

SC -> UI : Gives the sort options


UI -> CTRL :findProductsBy()

activate CTRL

CTRL -> SERV : findProductsBy()
activate SERV

SERV -> REP : findProductsBy()

REP --> SERV


SERV --> CTRL
deactivate SERV


CTRL --> UI
deactivate CTRL


UI --> SC : Shows the Product Catalog sorted and filtered

deactivate UI

deactivate SC

@enduml